package Interface;

 /*
        SAAT KITA MENGGUNANAKANN INTERFACE DALAM PROGRAM MAKA SECARA DEFAULT ACCESNYA SUDAH PUBLIC DAN KONTRAKNYA SUDAH ABSTRACT

        KITA HANYA BOLEH MENGISI FIELD DENGAN METHOD YANG TANPA ADA KURUNG KURAWALNYA
  */
public interface Brand extends CountryCar{
    void toyota();
    void bmw();
    void honda();


}
